# Generated by Django 4.2.11 on 2024-04-15 12:39

from django.db import migrations, models
import django.db.models.deletion
import utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("payment", "0001_initial"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("restored_at", models.DateTimeField(blank=True, null=True)),
                ("expiration_date", utils.fields.DateTimeWithoutTZField()),
                ("start_date", utils.fields.DateTimeWithoutTZField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("initial", "Initial"),
                            ("trial", "Trial"),
                            ("active", "Active"),
                            ("suspended", "Suspended"),
                            ("canceled", "Canceled"),
                            ("expired", "Expired"),
                        ],
                        default="expired",
                        max_length=64,
                    ),
                ),
                ("used_trial_days", models.IntegerField(default=0)),
                ("created", utils.fields.DateTimeWithoutTZField(auto_now_add=True)),
                ("updated", utils.fields.DateTimeWithoutTZField(auto_now=True)),
                (
                    "deleted_at",
                    utils.fields.DateTimeWithoutTZField(blank=True, null=True),
                ),
                (
                    "buyable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_subscriptions",
                        to="payment.buyable",
                    ),
                ),
                (
                    "purchase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="user_subscriptions",
                        to="payment.purchase",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to="user.user",
                    ),
                ),
            ],
            options={
                "db_table": "user_subscription",
            },
        ),
        migrations.CreateModel(
            name="UserSubscriptionChangeRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("expiration_date", utils.fields.DateTimeWithoutTZField()),
                ("start_date", utils.fields.DateTimeWithoutTZField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("initial", "Initial"),
                            ("trial", "Trial"),
                            ("active", "Active"),
                            ("suspended", "Suspended"),
                            ("canceled", "Canceled"),
                            ("expired", "Expired"),
                        ],
                        default="expired",
                        max_length=64,
                    ),
                ),
                ("used_trial_days", models.IntegerField(default=0)),
                ("created", utils.fields.DateTimeWithoutTZField(auto_now_add=True)),
                ("updated", utils.fields.DateTimeWithoutTZField(auto_now=True)),
                (
                    "buyable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_subscription_changes",
                        to="payment.buyable",
                    ),
                ),
                (
                    "purchase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="user_subscription_change",
                        to="payment.purchase",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription_changes",
                        to="user.user",
                    ),
                ),
                (
                    "user_subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="change_history",
                        to="subscription.usersubscription",
                    ),
                ),
            ],
            options={
                "db_table": "user_subscription_change_record",
            },
        ),
        migrations.AddConstraint(
            model_name="usersubscription",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("status", "active"), ("status", "trial"), _connector="OR"
                ),
                fields=("user",),
                name="unique_user_active_subscription",
            ),
        ),
    ]
