# Generated by Django 4.2.11 on 2024-04-15 12:39

import cloud_storage.constants.file_upload_constants
import cloud_storage.get_cloud_storage_client
from django.db import migrations, models
import utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TranslatedFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("restored_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=255, null=True)),
                ("extension", models.CharField(max_length=64)),
                (
                    "vendor_url",
                    models.CharField(
                        default="https://k2f7.or.idrivee2-60.com", max_length=255
                    ),
                ),
                (
                    "bucket_name",
                    models.CharField(
                        default=cloud_storage.constants.file_upload_constants.get_storage_bucket,
                        max_length=255,
                    ),
                ),
                (
                    "directory",
                    models.CharField(default="translated_file/", max_length=2048),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("IMAGE", "Image"),
                            ("AUDIO", "Audio"),
                            ("VIDEO", "Video"),
                        ],
                        max_length=64,
                    ),
                ),
                (
                    "vendor",
                    models.CharField(
                        default=cloud_storage.get_cloud_storage_client.get_cloud_storage_vendor,
                        max_length=64,
                    ),
                ),
                ("public", models.BooleanField(default=True)),
                ("created", utils.fields.DateTimeWithoutTZField(auto_now_add=True)),
                ("updated", utils.fields.DateTimeWithoutTZField(auto_now=True)),
                (
                    "deleted_at",
                    utils.fields.DateTimeWithoutTZField(blank=True, null=True),
                ),
            ],
            options={
                "db_table": "translated_file",
            },
        ),
        migrations.CreateModel(
            name="Translation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("restored_at", models.DateTimeField(blank=True, null=True)),
                ("text", models.CharField(max_length=512)),
                ("created", utils.fields.DateTimeWithoutTZField(auto_now_add=True)),
                ("updated", utils.fields.DateTimeWithoutTZField(auto_now=True)),
                (
                    "deleted_at",
                    utils.fields.DateTimeWithoutTZField(blank=True, null=True),
                ),
            ],
            options={
                "db_table": "translation",
            },
        ),
    ]
