# Generated by Django 4.2.11 on 2024-04-15 12:39

from django.db import migrations, models
import django.db.models.deletion
import user.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("common", "0001_initial"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="translation",
            name="locale",
            field=models.ForeignKey(
                default=user.models.Locale.get_default_id,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="translations",
                to="user.locale",
            ),
        ),
        migrations.AddField(
            model_name="translation",
            name="root",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="translations",
                to="common.translation",
            ),
        ),
        migrations.AddField(
            model_name="translatedfile",
            name="locale",
            field=models.ForeignKey(
                default=user.models.Locale.get_default_id,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="translated_files",
                to="user.locale",
            ),
        ),
        migrations.AddField(
            model_name="translatedfile",
            name="root",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="translations",
                to="common.translatedfile",
            ),
        ),
        migrations.AddConstraint(
            model_name="translation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("root", "locale"),
                name="unique_root_id_locale_id_if_not_deleted",
            ),
        ),
        migrations.AddConstraint(
            model_name="translation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("locale", "text"),
                name="unique_locale_id_text_if_not_deleted",
            ),
        ),
        migrations.AddConstraint(
            model_name="translatedfile",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("root", "locale"),
                name="unique_translated_file_root_id_locale_id_if_not_deleted",
            ),
        ),
        migrations.AddConstraint(
            model_name="translatedfile",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("name__isnull", True),
                        models.Q(("root_id", models.F("id")), _negated=True),
                    ),
                    models.Q(("name__isnull", False), ("root_id", models.F("id"))),
                    _connector="OR",
                ),
                name="translated_file_not_null_name_if_root",
            ),
        ),
    ]
