# Generated by Django 4.2.11 on 2024-04-15 12:39

from django.db import migrations, models
import utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("restored_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                ("created", utils.fields.DateTimeWithoutTZField(auto_now_add=True)),
                ("updated", utils.fields.DateTimeWithoutTZField(auto_now=True)),
                (
                    "deleted_at",
                    utils.fields.DateTimeWithoutTZField(blank=True, null=True),
                ),
            ],
            options={
                "db_table": "account",
            },
        ),
    ]
